AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    harvest

    Sample SAM Template for harvest

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 60

Resources:

    ProjectsFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: routes
            Handler: projects/projects.lambda_handler #TODO: ここを複数作る必要がある？？
            Runtime: python3.6
            Environment:
                Variables:
                    PARAM1: VALUE
            Events:
                OPTIONS:
                    Type: Api
                    Properties:
                        Path: /projects
                        Method: options
                GET:
                    Type: Api
                    Properties:
                        Path: /projects
                        Method: get
                POST:
                    Type: Api
                    Properties:
                        Path: /projects
                        Method: post
                GET_WITH_RESOURCE:
                    Type: Api
                    Properties:
                        Path: /projects/{project_id}
                        Method: get
                PUT_WITH_RESOURCE:
                    Type: Api
                    Properties:
                        Path: /projects/{project_id}
                        Method: put
                DELETE_WITH_RESOURCE:
                    Type: Api
                    Properties:
                        Path: /projects/{project_id}
                        Method: delete

    PlacesFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: routes
            Handler: places/places.lambda_handler #TODO: ここを複数作る必要がある？？
            Runtime: python3.6
            Environment:
                Variables:
                    PARAM1: VALUE
            Events:
                OPTIONS:
                    Type: Api
                    Properties:
                        Path: /projects/{project_id}/places
                        Method: options
                GET: #プロジェクト配下の全てのplaceを取得
                    Type: Api
                    Properties:
                        Path: /projects/{project_id}/places
                        Method: get
                POST: #project配下(root)に新規placeを作成
                    Type: Api
                    Properties:
                        Path: /projects/{project_id}/places
                        Method: post
                GET_WITH_RESOURCE: #place単体の情報を取得
                    Type: Api
                    Properties:
                        Path: /projects/{project_id}/places/{place_id}
                        Method: get
                GET_CHILDREN: #指定されたplaceのchildrenを取得
                    Type: Api
                    Properties:
                        Path: /projects/{project_id}/places/{place_id}/children
                        Method: get
                POST_WITH_RESOURCE: #指定されたplace_id配下にplaceを作成
                    Type: Api
                    Properties:
                        Path: /projects/{project_id}/places/{place_id}
                        Method: post
                PUT_WITH_RESOURCE: #placeの名前など単体の情報の何かを更新
                    Type: Api
                    Properties:
                        Path: /projects/{project_id}/places/{place_id}
                        Method: put
                DELETE_WITH_RESOURCE: #place単体を削除
                    Type: Api
                    Properties:
                        Path: /projects/{project_id}/places/{place_id}
                        Method: delete

Outputs:

    HelloWorldApi:
      Description: "API Gateway endpoint URL for Prod stage for Hello World function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"

    HelloWorldFunction:
      Description: "Hello World Lambda Function ARN"
      Value: !GetAtt HelloWorldFunction.Arn

    HelloWorldFunctionIamRole:
      Description: "Implicit IAM Role created for Hello World function"
      Value: !GetAtt HelloWorldFunctionRole.Arn
