AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    harvest

    Sample SAM Template for harvest

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 60

Resources:

    ProjectsFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: projects
            Handler: projects.lambda_handler #TODO: ここを複数作る必要がある？？
            Runtime: python3.6
            Environment:
                Variables:
                    PARAM1: VALUE
            Events:
                GET:
                    Type: Api
                    Properties:
                        Path: /projects
                        Method: get
                POST:
                    Type: Api
                    Properties:
                        Path: /projects
                        Method: post
                GET:
                    Type: Api
                    Properties:
                        Path: /projects/{proxy+}
                        Method: get
                PUT:
                    Type: Api
                    Properties:
                        Path: /projects/{proxy+}
                        Method: put
                DELETE:
                    Type: Api
                    Properties:
                        Path: /projects/{proxy+}
                        Method: delete

Outputs:

    HelloWorldApi:
      Description: "API Gateway endpoint URL for Prod stage for Hello World function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"

    HelloWorldFunction:
      Description: "Hello World Lambda Function ARN"
      Value: !GetAtt HelloWorldFunction.Arn

    HelloWorldFunctionIamRole:
      Description: "Implicit IAM Role created for Hello World function"
      Value: !GetAtt HelloWorldFunctionRole.Arn
